<?php
if(isset($track))
{
?>

<div class="container-fluid">
    <div class="row d-flex justify-content-center">
        <?php
        foreach ($track->tracks->items as $albums) {
        ?>
            <div class="tile border col-md-6 m-2 p-3 rounded-lg d-flex align-items-center">
                <img src="<?php echo $albums->album->images[0]->url ?>" style="width: 100px;height:100px;" class="rounded-lg" alt="">
                <div class="title ml-2">
                    <a class="m-0 p-0" href=<?php echo $albums->album->external_urls->spotify ?>>Open on spotify</a>
                    <p class="m-0 p-0"><?php echo $albums->name ?></p>
                    <p class="m-0 p-0"><?php echo $albums->id ?></p>
                    <p class="m-0 p-0"><?php echo $albums->uri ?></p>
                </div>
            </div>

        <?php
        }
        ?>
    </div>
</div>

<?php
}
?>






<?php
if(isset($album))
{
?>

<div class="container-fluid">
    <div class="row d-flex justify-content-center">
      
    <?php
        foreach ($album->albums->items as $item) {
            echo "<pre>";
            foreach($item->artists as $artist);
            {
                print_r($artist->external_urls->spotify);
                echo "<br>";
                print_r($artist->id);
                echo "<br>";
                print_r($artist->name);
                echo "<br>";
                print_r($artist->uri);
                echo "<br>";
                print_r($item->images[1]->url);
            }
            echo "</pre>";
            echo "<br>";
            // print_r($album1->external_urls);
            // print_r($album1->id);
            // print_r($album1->images[0]->url);
           
        ?>


          <?php
        }
        ?>
    </div>
</div>


<?php
}
?>



<?php
if(isset($artist))
{
 ?>
    <div class="container-fluid">
    <div class="row d-flex justify-content-center">
 <?php     
    foreach($artist->artists->items as $item)
    {
        ?> 
    <div class="tile border col-md-6 m-2 p-3 rounded-lg d-flex align-items-center">
        <?php
          if(isset($item->images[1]->url))
          {
              ?>
              <img src="<?php echo $item->images[1]->url ?>" style="width: 120px;height:120px;" class="rounded-lg" alt="">
              <?php  
          }
          ?>
           <div class="title ml-2">
           <a class="m-0 p-0" href=<?php echo $item->external_urls->spotify ?>>Open on spotify</a>
           <p class="m-0 p-0">Followers : <?php echo $item->followers->total ?></p>
           <p class="m-0 p-0">Item Id : <?php echo $item->id ?></p>
           <ul class="m-0 p-0">Genres :            
           <?php   
           if(count($item->genres) > 0)
           {
               foreach($item->genres as $k => $v)
               {
               ?>
                 <li class="ml-3 p-"><?php  print_r($v) ?></li>
                 
               <?php
               }
// print_r($item->genres);
           }   
                
      
      
      ?>
           </ul>
           </div>

         
       
    </div>
      <?php
    }
    ?>
    
    </div>
</div>

<?php
}
?>