<?php
if (isset($track)) {
    $track1 = json_decode(json_encode($track), true);
    echo "<pre>";
    // print_r($track1);
    if (isset($track1)) {
        foreach ($track1 as $k => $v) {
            if (isset($v)) {
                foreach ($v as $k1 => $v1) {
                    if ($k1 == 'items') {
                        foreach ($v1 as $k2 => $v2) {
                            foreach ($v2 as $k3 => $v3) {
                                if ($k3 == 'album') {
                                    foreach ($v3 as $k4 => $v4) {

                                        if($k4 == 'images')
                                        {
                                           // echo $k4;
                                           print_r($v4[0]['url']);
                                          
                                       }

                                        if ($k4 == 'artists') {
                                            foreach ($v4 as $k5 => $v5) {
                                              
                                                echo "<br>id = ";
                                                print_r($v5['id']);
                                                echo "<br>name = ";
                                                print_r($v5['name']);
                                                // echo "<br>type  =";
                                                // print_r($v5['type']);
                                                echo "<br>uri = ";
                                                print_r($v5['uri']);
                                                echo "<br>extermal = ";
                                                print_r($v5['external_urls']['spotify']);
                                                echo "<br><br><br>images=";
                                                if(isset($v5['images']))
                                                {
                                                    
                                                    print_r($v5['images']);
                                                    foreach($v5['images'] as $k6 => $v6)
                                                    {
                                                        echo $k6;
                                                        echo "<h1>images</h1>";
                                                        print_r($v6);
                                                    }
                                                }
                                                
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    die;
}
?>





<style>
    body {
        background: linear-gradient(to right, #c04848, #480048);
        min-height: 100vh
    }

    .text-gray {
        color: #aaa
    }

    img {
        height: 170px;
        width: 140px
    }
</style>


<div class="container py-5">
    <div class="row text-center text-white mb-5">
        <div class="col-lg-7 mx-auto">
            <h1 class="display-4">Product List</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <!-- List group-->
            <ul class="list-group shadow">
                <!-- list group item-->

                <li class="list-group-item">
                    <!-- Custom content-->

                    <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                        <div class="media-body order-2 order-lg-1">
                            <h5 class="mt-0 font-weight-bold mb-2">Apple iPhone XR (Red, 128 GB)</h5>
                            <p class="font-italic text-muted mb-0 small">128 GB ROM | 15.49 cm (6.1 inch) Display 12MP Rear Camera | 7MP Front Camera A12 Bionic Chip Processor</p>
                            <div class="d-flex align-items-center justify-content-between mt-1">
                                <h6 class="font-weight-bold my-2">₹64,999</h6>
                                <ul class="list-inline small">
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star-o text-gray"></i></li>
                                </ul>
                            </div>
                        </div><img src="https://i.imgur.com/KFojDGa.jpg" alt="Generic placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2">
                    </div> <!-- End -->
                </li> <!-- End -->
                <!-- list group item-->
                <!-- End -->
            </ul> <!-- End -->
        </div>
    </div>
</div>